name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
    
    - name: Run unit tests
      run: make test
